### ISSUE TITLE
Refactor build system

### ISSUE THREAD

**Issue by Fohlen** [tomatenquark/code#22]
The current build system does not support adding 3rd party dependencies easily.
I would like to refactor the build system with the following specification in mind:

- it needs to have support for XCode and MSBuild for debugging natively on these platforms
- ideally it uses CMake or any compatible tool of CLion to debug it on linux
- if the build system does not any longer fall back on system-installed libraries, it needs to ship these as files in the final build
  - these DLL/so/dylib files should not reside in the GitHub repository
  - on Windows this is already the case
    - remove these from the history if possible
  - on OSX and linux one has to take precautions about `LD_LIBRARY_PATH` in order to be able to find these files
  - it needs to support third party binary libraries, such as the asset bundler or Steam
- it should be fast (after caching the artifacts, at least as fast as the original build)
- it should allow for creating a `libtomatenquark` library which can be linked against (for building third party applications)

**Comment by stephanlachnit** [comment]
What about Meson? Meson is fast, prettier than CMake and works with both XCode and Visual Studio.
After taking a look at the Makefile, it doesn't look too hard. Maybe I'll give it a try.

**Comment by Fohlen** [comment]
Hey @stephanlachnit I'm all open for ideas.
Honestly I'm not very involved with build systems and if somebody has knowledge around bazel or Meson I'm very glad.

Bear in mind this is (I believe) a large task because:

- you need to add SDL2, SDL2-mixer, SDL2-image, zlib and curl as a dependency
- on Windows one needs to copy these dependencies to the output folder (see `lib` and `bin` folders)
- on OSX you need to link using the `-framework` option
- generally we are compiler-neutral so: GCC on linux, clang on OSX, MSVC on Windows

Ideally this issue removes binary files from the repository.
If you think this sounds like a task for you I'd be delighted to see a PR!
If you need further help let me know here or on our [Discord](https://discord.gg/47rkQar).

All the best

**Comment by stephanlachnit** [comment]
Please not Bazel as contributing requires signing a CLA.

The good thing about Meson that is has a dependency tool called wrap. Basically you don't need to copy Zlib etc, Meson will download it for you if it's missing.

Meson itself is written OS neutral, i.e. you don't call gcc itself, Meson will decide which compiler to use (ofc you can still specify it if you want).

I can take a look into it, but right now I'm short on time.

**Comment by Calinou** [comment]
One issue with Meson's wrap system is that it seems to have much less adoption compared to [vcpkg](https://github.com/microsoft/vcpkg), which integrates with CMake. That said, I'm fine with using Meson.

**Comment by stephanlachnit** [comment]
That's true. There is a WrapDB entry for SDL2 and Zlib, but not for example SDL2 image and SDL2 mixer. That being said, I think CMake is pretty ugly and I rather write Meson files for these projects than working with CMake.

**Comment by Fohlen** [comment]
While tampering with the SteamWorks SDK I have noticed that prioritising this is unavoidable (as otherwise the number of VS and XCode projects explodes).

What is left to do:

- [x] test if it builds on Windows and Linux (it runs on OSX)
- [x] properly split up dependencies because `server` and `master` targets will not need `sdl2`
- [x] test packaging on all platforms (copy DLL on Windows, dylib on Apple and so on Linux)
- [ ] set up 'installation' on all platforms
- [x] test integration with Visual Studio and XCode (or CLion, idc, something that runs on Mac)
- [ ] rewrite continuous integration and continuous deployment pipeline
- [ ] update build instructions

**Comment by Fohlen** [comment]
The updated system uses CMake + vcpkg and runs on all three platforms. Hooray to that. Will soon draft a PR to close this ticket.
