### ISSUE TITLE
Add SteamWorks integration

### ISSUE THREAD

**Issue by Fohlen** [tomatenquark/code#3]
We want to have SteamWorks integration in the game. Have a look at the [SDK documentation](https://partner.steamgames.com/doc/sdk).

In particular we want the following features:

- indicate in Steam that you are playing the game
- show to your friends in which server you are playing
  - when clicking the "Show server" button it should show the server and who is currently playing (which mode, time, name)
- make it possible to join the same server as your friends

**Comment by Croydon** [comment]
Will the Steam integration stay optional or will Tomatenquark be distributed as Steam-only?

**Comment by Fohlen** [comment]
The Steam integration should always be optional. I imagine something like a `ENABLE_STEAM` compilation flag that will enable/disable the integration (similar to Red Eclipse)

**Comment by Fohlen** [comment]
Okay, a first step to take is:

- include Steam SDK according to their guide
- add a AUTH network package for Steam authentication
- add a server variable so the server can decide between
  - disabled mode (no Steam verification is performed)
  - optional mode (clients can and can not authenticate via Steam)
  - locked mode (clients must authenticate via Steam otherwise they cannot play)

This helps massively fight cheaters because of the VAC.
Further some remarks:

- add a compilation flag (`ENABLE_STEAM`) to all platforms
- never commit or compile the SteamWorks SDK into Github/Github Releases because it is proprietary
- additionally offer the server for download via the SteamWorks SDK ('App Tool with custom AppID')

This seems straightforward to be done and I will start working on it after the release fragfest.

**Comment by Fohlen** [comment]
We can use the following functionality https://framagit.org/khanat/khanat/blob/93f5836fd5372c0b07d0be569f9c8e285239d899/code/CMakeModules/FindSteam.cmake to work with Steam. This means that a implementation can be agnostic (just drop the SDK folder anywhere and it will automagically add `ENABLE_STEAM` as a compilation definition).
