### ISSUE TITLE
Can only play 1 round of bot match

### ISSUE THREAD

**Issue by aproposnix** [tomatenquark/code#38]
Currently, when you create a bot match, after the match ends the user is thrown into an edit map.

Expected result: A new round of the same map should be played [cycling through maps would be cooler though]

I'm using the current version from Steam. 
I'm running Ubuntu 20.04 (with Unity) 

The game runs awesome! Well done! 

Here's a screen of the game after the "intermission" - notice the map failure... 

![Screenshot from 2020-05-27 11-01-44](https://user-images.githubusercontent.com/6204273/82999674-a749c180-a009-11ea-9036-f402540f6f56.png)

**Comment by Calinou** [comment]
This is probably an issue with map rotation. I noticed this while setting up my dedicated server: it starts on an empty map.

**Comment by Fohlen** [comment]
Closed by Salatiel in 5543a44cf314bbfaa44c66541dfd32e58024135b
