### ISSUE TITLE
Add 32 bit executables to linux

### ISSUE THREAD

**Issue by Fohlen** [tomatenquark/code#39]
There are players on old machines on linux. Add 32 bit support for them.

**Comment by Calinou** [comment]
I was really surprised to find there are still people trying to play games on 32-bit Linux today. Is there any reason for them using 32-bit Linux?

In contrast, 32-bit Windows is a whole different can of worms; people are sometimes stuck with a preinstalled OEM version and can't replace it easily.

**Comment by Fohlen** [comment]
I was surprised by this fact as well. But there were some players reporting to be apparently playing on a toaster. This is also why there was no 32-bit linux support for now. But using the `-m32` flag should suffice.

**Comment by Fohlen** [comment]
This should be solved by #40

**Comment by Fohlen** [comment]
Since there is NO official support for `x86-linux` in `vcpkg` it seems like a no-op to me, even when loosing players.
