### ISSUE TITLE
No BUILD.md

### ISSUE THREAD

**Issue by zlyfer** [tomatenquark/code#5]
I would like to modify the server and build Tomatenquark by myself. However despite the README.md linking to it, there is no BUILD.md file which - as I hoped - includes building instructions.

**Comment by Fohlen** [comment]
Hey you are right I forgot to add this file.
The instructions for building can be found here:

https://github.com/tomatenquark/code/blob/master/.github/workflows/continous-integration.yml

When I'll find time for documentation I will add the missing instructions, or would you like to add a PR?

**Comment by zlyfer** [comment]
I created a [pull request](https://github.com/tomatenquark/code/pull/6) to add the build instructions. I only tested building on Debian, therefore I cannot verify if the instructions for MacOS and Windows are sufficient.
