### ISSUE TITLE
Game Will Not Run on MacOS Catalina

### ISSUE THREAD

**Issue by ghost** [tomatenquark/code#59]
![Screen_Shot_2020-09-10_at_3 40 53_PM](https://user-images.githubusercontent.com/71099713/92795442-60949300-f37e-11ea-8819-4628355d11bf.png)
![Screen Shot 2020-09-10 at 3 58 22 PM](https://user-images.githubusercontent.com/71099713/92795571-7a35da80-f37e-11ea-9d51-31825ecedcf3.png)

I tried loading the MacOS client from github, I get error message 1.
I try loading the MacOS Steam build, I get error message 2 after the runtime crashes.

This is happening to all users on Catalina. The Steam description for this app says it should be 64 bit and work on 10.15+ Catalina OS.

**Comment by Calinou** [comment]
Follow the instructions on [this page](https://disable-gatekeeper.github.io/) to run Tomatenquark, as it's unsigned.

**Comment by ghost** [comment]
Hi this did not work. I had already set up my mac to run unsigned apps with my permission. There must be something wrong with the Mac exe.

**Comment by ghost** [comment]
![Screen Shot 2020-09-12 at 9 15 39 PM](https://user-images.githubusercontent.com/71099713/93007970-494fd400-f53d-11ea-8cee-fc5f1687ed4d.png)
![Screen Shot 2020-09-12 at 9 16 28 PM](https://user-images.githubusercontent.com/71099713/93007971-49e86a80-f53d-11ea-9e6f-05e1d0451597.png)

**Comment by qreeves** [comment]
You need to replace `/path/to/tomatenquark.app` with the actual path to the app.

**Comment by Fohlen** [comment]
The current Tomatenquark OSX bundle is broken. I need to rebuild a new bundle and upload it to Steam. My apologies.

**Comment by k1aatu34** [comment]
> You need to replace `/path/to/tomatenquark.app` with the actual path to the app.

I've already done that and no dice. Like Fohlen says, the bundle just needs to be rebuilt.

**Comment by Fohlen** [comment]
For a quick fix you may use the following bundle: https://github.com/tomatenquark/code/releases/download/v0.2.2/tomatenquark_macos.zip

Uploading a new version to Steam is necessary to make it work, however that is a tedious process.

**Comment by Fohlen** [comment]
The latest release on Steam will work. Have fun.
