### ISSUE TITLE
Hide Health/Ammo HUD by default in Instagib

### ISSUE THREAD

**Issue by Delphik** [tomatenquark/code#62]
The HUD elements for health and ammo serve no practical purpose in Instagib gamemodes, and should be hidden by default for immersions sake. 

Health is absolutely useless, and it's not likely a player runs out of ammo in instagib. (Worth raising the question of whether ammo should just be infinite)

**Comment by yellowberryHN** [comment]
I feel like it could be confusing to someone who doesn't understand the concept of Instagib to have it disabled by default.

**Comment by Delphik** [comment]
The gamemode is explained in the menu for selecting gamemodes. I personally don't think instagib needs much of an explanation, but perhaps this makes more sense initially as an opt in, rather than default.

**Comment by janitor-raus** [comment]
I'd say you can remove the health, use an infinity symbol for the ammo counter.

**Comment by coornio** [comment]
I'd say you can remove the health, use an infinity symbol for the ammo counter.

**Comment by Delphik** [comment]
The ammo isn't functionally infinite yet, it still would start at 100 in the background so that would be misleading, although I feel the value should probably be changed to be infinite.

**Comment by qreeves** [comment]
Typically, instagib should show "1" for the amount of health. It's usually more desirable to have the HUD remain consistent than hide information based on context like this.

**Comment by Delphik** [comment]
It could be argued that the lack of the expected health and ammo do provide context about the gamemode, like how "Hardcore" modes are used in modern shooters.

**Comment by SalatielSauer** [comment]
I think we should keep consistency, in effic we also spawn with weapons and there are no ammo pickups, but it would make no sense to make them infinite or disable their icons just because we already know how the mode works...

on a side note, in sauer we used to play instagib hideseek, the hider couldn’t kill the seeker but could use the rifle to escape, his ammo being finite was an important feature :P

**Comment by Delphik** [comment]
![Screenshot_20201116_143224](https://user-images.githubusercontent.com/25359595/99298972-8d4ea600-2818-11eb-9907-caccb9ea5c77.png)

The community has spoken, looks like if we do this it needs to be opt in.
